import os
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
EOD_STOCK_KEY1 = os.getenv('EOD_STOCK_KEY1')
EOD_STOCK_KEY2 = os.getenv('EOD_STOCK_KEY2')

BBW_DAILY_INTERVAL = '1day'
BBW_INTRADAY_INTERVAL = '30min'
BBW_STANDARD_DEVIATION = '2'
BBW_TIME_PERIOD = '20'
BBW_OUTPUT_SIZE = '1000'

FREE_STOCK_SLEEP_TIME = 8
INTRA_DAY_BATCH_SLEEP_TIME = 1801