import os

DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
EOD_STOCK_KEY1 = os.getenv('EOD_STOCK_KEY1')
EOD_STOCK_KEY2 = os.getenv('EOD_STOCK_KEY2')
TWELVE_API_BASE_URL = os.getenv('TWELVE_API_BASE_URL')
RAPID_API_HOST = os.getenv('RAPID_API_HOST')
